import type { Programme, MatchResultsGroup, ShortlistItem, Relationship, ActorTableRow } from "@/types";

export const MOCK_PROGRAMMES: Programme[] = [
  {
    id: "prog-001",
    name: "Global Fintech Accelerator 2024",
    description:
      "An intensive 10-week program designed to scale high-growth fintech startups through mentorship, funding access, and strategic partnerships.",
    category: "Fintech",
    status: "published",
    startDate: "2024-10-12",
    endDate: "2024-12-15",
    coverImage: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&q=80",
    requirements: {
      targetIndustry: "Financial Technology",
      targetCountry: "Malaysia",
      targetCompanyStage: "Seed",
      requiredMentors: 5,
      requiredCompanies: 10,
      requiredPartners: 3,
      requiredServiceProviders: 2,
      eligibilityCriteria:
        "Startups must be incorporated, have an MVP, and be in the Seed stage.",
    },
    progress: { label: "Applications", value: 85, status: "85% Capacity" },
    organiserId: "org-001",
    organiserName: "Sarah Chen",
    publishedAt: "2024-10-01",
    createdAt: "2024-09-15",
    updatedAt: "2024-10-01",
  },
  {
    id: "prog-002",
    name: "AI in Healthcare Symposium",
    description:
      "A gathering of top minds to discuss the ethical and practical integration of AI within healthcare systems across Southeast Asia.",
    category: "Healthcare",
    status: "pending_review",
    startDate: "2024-11-05",
    coverImage: "https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=600&q=80",
    requirements: {
      targetIndustry: "Healthcare & Life Sciences",
      targetCountry: "Singapore",
      targetCompanyStage: "Any",
      requiredMentors: 8,
      requiredCompanies: 15,
      requiredPartners: 4,
      requiredServiceProviders: 3,
      eligibilityCriteria:
        "Open to all healthcare-focused startups and research organisations.",
    },
    progress: { label: "Setup Completion", value: 60, status: "Awaiting Approval" },
    organiserId: "org-001",
    organiserName: "Sarah Chen",
    submittedAt: "2024-10-20",
    createdAt: "2024-10-01",
    updatedAt: "2024-10-20",
  },
  {
    id: "prog-003",
    name: "Sustainable Urban Futures",
    description:
      "An incubation program focused on green technologies and smart city solutions for the next generation of sustainable urban living.",
    category: "Sustainability",
    status: "draft",
    startDate: "2025-01-01",
    coverImage: "https://images.unsplash.com/photo-1518005068251-37900150dfca?w=600&q=80",
    requirements: {
      targetIndustry: "Clean Technology",
      targetCountry: "Malaysia",
      targetCompanyStage: "Pre-Seed",
      requiredMentors: 4,
      requiredCompanies: 8,
      requiredPartners: 3,
      requiredServiceProviders: 2,
      eligibilityCriteria:
        "Early-stage startups with a sustainability-focused product or service.",
    },
    progress: { label: "Draft Progress", value: 40, status: "40%" },
    organiserId: "org-001",
    organiserName: "Sarah Chen",
    createdAt: "2024-10-10",
    updatedAt: "2024-10-15",
  },
  {
    id: "prog-004",
    name: "AgriTech Innovation Fund",
    description:
      "Supporting agricultural technology startups with funding, mentorship, and market access across ASEAN.",
    category: "AgriTech",
    status: "submitted",
    startDate: "2025-03-01",
    coverImage: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&q=80",
    requirements: {
      targetIndustry: "Agriculture Technology",
      targetCountry: "Indonesia",
      targetCompanyStage: "Seed",
      requiredMentors: 6,
      requiredCompanies: 12,
      requiredPartners: 4,
      requiredServiceProviders: 2,
      eligibilityCriteria:
        "AgriTech startups with a working prototype and initial market traction.",
    },
    progress: { label: "Submission", value: 100, status: "Under Admin Review" },
    organiserId: "org-001",
    organiserName: "Sarah Chen",
    submittedAt: "2024-10-22",
    createdAt: "2024-10-05",
    updatedAt: "2024-10-22",
  },
];

export const MOCK_MATCH_RESULTS: MatchResultsGroup = {
  companies: [
    {
      id: "match-c-001",
      actorId: "comp-001",
      actorType: "company",
      actorName: "PayFlow Technologies",
      profileSummary: "B2B payment infrastructure startup targeting SMEs in Southeast Asia with embedded finance solutions.",
      matchScore: 94,
      matchTier: "Excellent",
      aiExplanation: "Strong alignment with programme's fintech focus and Seed stage requirement. Operating in target market with proven traction.",
      availabilityLabel: "Available",
      isAvailable: true,
      tags: ["Fintech", "Seed", "Malaysia"],
    },
    {
      id: "match-c-002",
      actorId: "comp-002",
      actorType: "company",
      actorName: "CreditBridge AI",
      profileSummary: "AI-driven credit scoring platform for underserved populations in emerging markets.",
      matchScore: 88,
      matchTier: "Strong",
      aiExplanation: "High match on industry and company stage. AI-native product fits programme's innovation mandate.",
      availabilityLabel: "Available",
      isAvailable: true,
      tags: ["Fintech", "AI", "Seed"],
    },
    {
      id: "match-c-003",
      actorId: "comp-003",
      actorType: "company",
      actorName: "InsureNow",
      profileSummary: "Insurtech startup offering micro-insurance products via mobile for gig workers.",
      matchScore: 76,
      matchTier: "Strong",
      aiExplanation: "Good sector match in financial services. Micro-insurance addresses an underserved segment relevant to the programme.",
      availabilityLabel: "Limited Slots",
      isAvailable: true,
      tags: ["Insurtech", "Mobile", "Seed"],
    },
  ],
  mentors: [
    {
      id: "match-m-001",
      actorId: "ment-001",
      actorType: "mentor",
      actorName: "Dr. Aisha Ramlan",
      profileSummary: "Former VP at CIMB Fintech; 15 years in financial regulation and digital banking. Expert in Southeast Asian market entry.",
      matchScore: 96,
      matchTier: "Excellent",
      aiExplanation: "Perfect expertise alignment. Deep regulatory knowledge critical for fintech startups navigating compliance.",
      availabilityLabel: "3 slots available",
      isAvailable: true,
      tags: ["Fintech", "Regulation", "Digital Banking"],
    },
    {
      id: "match-m-002",
      actorId: "ment-002",
      actorType: "mentor",
      actorName: "James Ng",
      profileSummary: "Venture Partner at Vertex Ventures. Specialises in scaling B2B SaaS and fintech companies in ASEAN.",
      matchScore: 89,
      matchTier: "Strong",
      aiExplanation: "Strong VC and growth expertise. Has helped 8 fintech companies reach Series A from Seed stage.",
      availabilityLabel: "2 slots available",
      isAvailable: true,
      tags: ["Venture", "B2B SaaS", "Growth"],
    },
  ],
  partners: [
    {
      id: "match-p-001",
      actorId: "part-001",
      actorType: "partner",
      actorName: "Maybank Innovation Hub",
      profileSummary: "Corporate innovation arm of Maybank, Malaysia's largest bank. Provides banking APIs, pilots, and co-investment opportunities.",
      matchScore: 92,
      matchTier: "Excellent",
      aiExplanation: "Strategic corporate partner for fintech startups. Direct access to banking infrastructure and customer base.",
      availabilityLabel: "Active partnership",
      isAvailable: true,
      tags: ["Banking", "Corporate", "Malaysia"],
    },
    {
      id: "match-p-002",
      actorId: "part-002",
      actorType: "partner",
      actorName: "MDEC",
      profileSummary: "Malaysia Digital Economy Corporation. Supports digital innovation through grants, market access, and global connections.",
      matchScore: 85,
      matchTier: "Strong",
      aiExplanation: "Government agency partnership adds credibility and provides regulatory sandboxing access for fintech programmes.",
      availabilityLabel: "Available",
      isAvailable: true,
      tags: ["Government", "Digital Economy", "Grants"],
    },
  ],
  serviceProviders: [
    {
      id: "match-sp-001",
      actorId: "sp-001",
      actorType: "service_provider",
      actorName: "LegalEdge Consulting",
      profileSummary: "Boutique legal firm specialising in startup incorporation, IP protection, and fintech regulatory compliance.",
      matchScore: 90,
      matchTier: "Excellent",
      aiExplanation: "Essential service for fintech startups. Deep expertise in BNM compliance and financial licensing requirements.",
      availabilityLabel: "High capacity",
      isAvailable: true,
      tags: ["Legal", "Compliance", "Fintech"],
    },
    {
      id: "match-sp-002",
      actorId: "sp-002",
      actorType: "service_provider",
      actorName: "CloudStack Solutions",
      profileSummary: "Cloud infrastructure and DevOps services provider specialised in fintech-grade security and compliance.",
      matchScore: 78,
      matchTier: "Strong",
      aiExplanation: "Provides secure, scalable infrastructure critical for fintech payment processing applications.",
      availabilityLabel: "Available",
      isAvailable: true,
      tags: ["Cloud", "DevOps", "Security"],
    },
  ],
};

export const MOCK_SHORTLIST: ShortlistItem[] = [
  {
    id: "sl-001",
    programmeId: "prog-001",
    matchResultId: "match-c-001",
    actorId: "comp-001",
    actorType: "company",
    actorName: "PayFlow Technologies",
    matchScore: 94,
    addedAt: "2024-10-18",
    addedBy: "Sarah Chen",
    isAdminSelected: true,
  },
  {
    id: "sl-002",
    programmeId: "prog-001",
    matchResultId: "match-m-001",
    actorId: "ment-001",
    actorType: "mentor",
    actorName: "Dr. Aisha Ramlan",
    matchScore: 96,
    addedAt: "2024-10-18",
    addedBy: "Sarah Chen",
    isAdminSelected: true,
  },
  {
    id: "sl-003",
    programmeId: "prog-001",
    matchResultId: "match-p-001",
    actorId: "part-001",
    actorType: "partner",
    actorName: "Maybank Innovation Hub",
    matchScore: 92,
    addedAt: "2024-10-18",
    addedBy: "Sarah Chen",
    isAdminSelected: false,
  },
];

export const MOCK_RELATIONSHIPS: Relationship[] = [
  {
    id: "rel-001",
    type: "company_mentor",
    programmeId: "prog-001",
    programmeName: "Global Fintech Accelerator 2024",
    sourceId: "comp-001",
    sourceName: "PayFlow Technologies",
    sourceType: "Company",
    targetId: "ment-001",
    targetName: "Dr. Aisha Ramlan",
    targetType: "Mentor",
    status: "active",
    establishedAt: "2024-10-12",
  },
  {
    id: "rel-002",
    type: "company_partner",
    programmeId: "prog-001",
    programmeName: "Global Fintech Accelerator 2024",
    sourceId: "comp-001",
    sourceName: "PayFlow Technologies",
    sourceType: "Company",
    targetId: "part-001",
    targetName: "Maybank Innovation Hub",
    targetType: "Partner",
    status: "active",
    establishedAt: "2024-10-12",
  },
  {
    id: "rel-003",
    type: "company_service_provider",
    programmeId: "prog-001",
    programmeName: "Global Fintech Accelerator 2024",
    sourceId: "comp-001",
    sourceName: "PayFlow Technologies",
    sourceType: "Company",
    targetId: "sp-001",
    targetName: "LegalEdge Consulting",
    targetType: "Service Provider",
    status: "active",
    establishedAt: "2024-10-12",
  },
  {
    id: "rel-004",
    type: "company_programme",
    programmeId: "prog-001",
    programmeName: "Global Fintech Accelerator 2024",
    sourceId: "comp-002",
    sourceName: "CreditBridge AI",
    sourceType: "Company",
    targetId: "prog-001",
    targetName: "Global Fintech Accelerator 2024",
    targetType: "Programme",
    status: "active",
    establishedAt: "2024-10-12",
  },
];

export const MOCK_ACTORS: ActorTableRow[] = [
  { id: "comp-001", name: "PayFlow Technologies", type: "company", category: "Fintech", country: "Malaysia", status: "active", registeredAt: "2024-08-01" },
  { id: "comp-002", name: "CreditBridge AI", type: "company", category: "Fintech", country: "Singapore", status: "active", registeredAt: "2024-08-10" },
  { id: "comp-003", name: "InsureNow", type: "company", category: "Insurtech", country: "Malaysia", status: "active", registeredAt: "2024-08-15" },
  { id: "ment-001", name: "Dr. Aisha Ramlan", type: "mentor", category: "Fintech / Regulation", country: "Malaysia", status: "active", registeredAt: "2024-07-20" },
  { id: "ment-002", name: "James Ng", type: "mentor", category: "Venture / Growth", country: "Singapore", status: "active", registeredAt: "2024-07-25" },
  { id: "part-001", name: "Maybank Innovation Hub", type: "partner", category: "Banking", country: "Malaysia", status: "active", registeredAt: "2024-06-01" },
  { id: "part-002", name: "MDEC", type: "partner", category: "Government", country: "Malaysia", status: "active", registeredAt: "2024-06-05" },
  { id: "sp-001", name: "LegalEdge Consulting", type: "service_provider", category: "Legal", country: "Malaysia", status: "active", registeredAt: "2024-07-01" },
  { id: "sp-002", name: "CloudStack Solutions", type: "service_provider", category: "Cloud Infrastructure", country: "Singapore", status: "active", registeredAt: "2024-07-10" },
];

export const ADMIN_STATS = {
  pendingSubmissions: 4,
  publishedProgrammes: 3,
  activeProgrammes: 2,
  totalActors: 42,
};

export const ORGANIZER_STATS = {
  totalProgrammes: 12,
  draft: 3,
  submittedToAdmin: 4,
  pendingReview: 2,
  published: 3,
};
